version: '3'
services:
  api:
    build: .
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file: .env
    networks:
      - redis-net
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
volumes:
  redis-data:
networks:
  redis-net: